//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voitures
    {
        public System.Guid VoitureId { get; set; }
        public Nullable<System.Guid> MarqueId { get; set; }
        public string Modèle { get; set; }
        public Nullable<int> Kilometrage { get; set; }
        public string Cylindree { get; set; }
        public string Couleur { get; set; }
        public Nullable<System.DateTime> Annee { get; set; }
        public string Puissance { get; set; }
        public string Energie { get; set; }
        public Nullable<double> Prix { get; set; }
        public byte[] Photo { get; set; }
    }
}
